name: Upstream Sync

on:
  schedule:
    - cron: "0 0 * * *"   # Runs every day at 00:00 UTC
  workflow_dispatch:      # Allows manual trigger from the Actions tab

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: ButterscotchRunner/Butterscotch

          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          echo "[Error] Sync failed. This can happen when there are conflicting file changes."
          exit 1